### ISSUE TITLE
Mismarked interfaces for built-in up/down rules in v8?

### ISSUE THREAD

**Issue by Alamei** [FreshPr/FreshJR_QOS#1]
In reviewing the changes for version 8, I saw a couple of lines that _appear_ to be targeting the wrong interface for what they're intended to do, but I'm not incredibly familiar with router code, so I wanted to ask about them rather than submit a pull request for something I don't truly understand. 

Is there a reason that the Advertising downstream TC rule on line 236 is targeting the eth0 interface while the rest of the downstream TC rules are targeting br0?

Similarly, is there a reason the HTTPS recreation rule for upstream on line 253 is targeting br0 instead of eth0? I see that one is marked for prio 20 instead of 22, so I figured perhaps it's not just intended to be an upstream reflection of the rule on line 227.

**Comment by FreshJR07** [comment]
Thanks for the report!  All three concerns were valid bug reports.

Sorry it took so long to respond.  I was primarily active with SNB forums instead of github.  I will be checking github more often!

--

I know the script is convoluted in how it is applied or parameters are passed but that is because I am working around limitations of a rigid predefined structure.

Heres some quick info if you'd like to get a little more familiar with certain references:

TC has hardcoded interface names
br0 - represents download
eth0 - represents upload

iptables has varying interface names
br0 - represents download
eth0/ppp0/vlanXXX/etc - can represent upload.  
(The upload interface gets passed into the script automatically when using RMerlin firmware and is read manually from iptables post-QOS launch in AsusWRT setups.  I included a manual override exists just incase someone is having issues with auto-detection)

That's why the names interface names don't seem to match between TC & iptables..

As you deduced 0x8 filters are for download and 0x4 filters are for upload.

Prio is pre-cacluated depending on which order I need to rule evaluated for it to take effect.
 In general TC is a continuous if-statement tree, so bulk traffic at attempted to be caught at lower prios.

--

I missed the edits required when copy/pasting rules.
